### PR TITLE
Update to 1.12

### PR DESCRIPTION
**Pull request by phroa**

### CODE REVIEW

**Comment by mattmess1221** [comment]
You should update mixin to 0.6.10

**Comment by rowanos** [comment]
Is there any way to download this as a liteloader mod currently?

**Comment by AeSix** [comment]
If you can build with gradle (which I'm not capable of doing, becuase brain refuses to figure it out), you can get it for 1.12 - but there seems to be no pre-built files for download for 1.12, just 1.11.2 :(
I've been waiting patiently, but it would be nice ot have a download :D

**Comment by dags-** [comment]
Oops yeah, it's up on releases now. Sorry for the wait!

(+ thanks for the PR!)

**Pull request merged**
